game-duration: 5400
playerSkips: 3
teamSkips : 1
swaps: 1
reset-advancements-on-finish: true
first-startup: true

### --- Add items/objectives that should be excluded. Restart the server afterwards --- ###
exclude:
    items:
        - WATER
        - DECORATED_POT
        - POWDER_SNOW
        - CHAIN_COMMAND_BLOCK
        - WATER_CAULDRON
        - LAVA_CAULDRON
        - COMMAND_BLOCK_MINECART
        - COMMAND_BLOCK
        - POWDER_SNOW_CAULDRON
        - REPEATING_COMMAND_BLOCK
        - BEDROCK
        - AIR
        - FIRE
        - SOUL_FIRE
        - END_PORTAL_FRAME
        - NETHER_PORTAL
        - END_PORTAL
        - LIGHT
        - END_GATEWAY
        - TALL_SEAGRASS
        - VOID_AIR
        - PISTON_HEAD
        - MOVING_PISTON
        - WRITTEN_BOOK
        - TORCHFLOWER_SEEDS
        - JIGSAW
        - TIPPED_ARROW
        - LAVA
        - WATER_CAULDRON
        - STRUCTURE_VOID
        - BARRIER
        - DEBUG_STICK
        - FARMLAND
        - STRUCTURE_BLOCK
        - BUBBLE_COLUMN
        - CAVE_AIR
        - KNOWLEDGE_BOOK
        - DIRT_PATH
        - REDSTONE_WIRE
        - FROSTED_ICE
        - REINFORCED_DEEPSLATE
        - BUDDING_AMETHYST
        - CHORUS_PLANT
        - MOB_SPAWNER
        - SPAWNER
        - LEASH_KNOT
        - PLAYER_HEAD
        - LINGERING_POTION
        - SPLASH_POTION
        - POTION
        - OMINOUS_TRIAL_SPAWNER
        - TRIAL_SPAWNER
        - SUSPICIOUS_GRAVEL
        - SUSPICIOUS_SAND
        - FROGSPAWN
    mobs:
        - ACACIA_BOAT
        - ACACIA_CHEST_BOAT
        - AREA_EFFECT_CLOUD
        - ARMOR_STAND
        - ARROW
        - BAMBOO_CHEST_RAFT
        - BAMBOO_RAFT
        - BIRCH_BOAT
        - BIRCH_CHEST_BOAT
        - BLOCK_DISPLAY
        - BREEZE_WIND_CHARGE
        - CHERRY_BOAT
        - CHERRY_CHEST_BOAT
        - CHEST_MINECART
        - COMMAND_BLOCK_MINECART
        - DARK_OAK_BOAT
        - DARK_OAK_CHEST_BOAT
        - DRAGON_FIREBALL
        - EGG
        - END_CRYSTAL
        - ENDER_PEARL
        - EVOKER_FANGS
        - EXPERIENCE_BOTTLE
        - EXPERIENCE_ORB
        - EYE_OF_ENDER
        - FALLING_BLOCK
        - FIREBALL
        - FIREWORK_ROCKET
        - FISHING_BOBBER
        - FURNACE_MINECART
        - GIANT
        - GLOW_ITEM_FRAME
        - HOPPER_MINECART
        - ILLUSIONER
        - INTERACTION
        - ITEM
        - ITEM_DISPLAY
        - ITEM_FRAME
        - JUNGLE_BOAT
        - JUNGLE_CHEST_BOAT
        - LEASH_KNOT
        - LIGHTNING_BOLT
        - LINGERING_POTION
        - LLAMA_SPIT
        - MANGROVE_BOAT
        - MANGROVE_CHEST_BOAT
        - MARKER
        - MINECART
        - OAK_BOAT
        - OAK_CHEST_BOAT
        - OMINOUS_ITEM_SPAWNER
        - PAINTING
        - PALE_OAK_BOAT
        - PALE_OAK_CHEST_BOAT
        - SHULKER_BULLET
        - SMALL_FIREBALL
        - SNOWBALL
        - SPAWNER_MINECART
        - SPECTRAL_ARROW
        - SPLASH_POTION
        - SPRUCE_BOAT
        - SPRUCE_CHEST_BOAT
        - TEXT_DISPLAY
        - TNT
        - TNT_MINECART
        - TRIDENT
        - UNKNOWN
        - WIND_CHARGE
        - WITHER_SKULL
        - ZOMBIE_HORSE
    biomes:
        - THE_VOID

    # default height range: -63 - 320
    heights:
    advancements:
    structures:
