name: ForceBattlePlugin
version: 1.15.0
main: net.fameless.forcebattle.ForceBattlePlugin
api-version: '1.20'
load: STARTUP

commands:
  team:
  menu:
    aliases: [settings]
  points:
  timer:
  reset:
  skip:
  exclude:
  joker:
  result:
  backpack:
  newworld: